services:
  postgres:
    image: postgres:16
    container_name: erp-postgres
    environment:
      POSTGRES_DB: erpdb
      POSTGRES_USER: erpuser
      POSTGRES_PASSWORD: erppass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
